Repository fweik/nrng, pull requests merged in 2020-12, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#9 Added cmake library alias
  .gitignore
  CMakeLists.txt
Labels: enhancement

#12 ci: Set gcc version to 10
  .github/workflows/build_cmake.yml
Labels: ci

#17 Fixed appveyor config
  .clang-tidy
  appveyor.yml
  include/nrng/iota.hpp
  tests/CMakeLists.txt
  tests/iota.test.cpp
Labels: ci, enhancement

#22 reduce + test
  include/nrng/reduce.hpp
  include/nrng/type_traits.hpp
  tests/reduce.test.cpp
Labels: enhancement

#23 cmake: Limit doxygen to include/
  cmake/Doxygen.cmake
Labels: documentation, enhancement

#33 Bump Doctest version to 2.4.1
  .clang-tidy
  external/doctest/include/doctest/doctest.h
Labels: enhancement

#34 Docs
  README.md
Labels: documentation, enhancement

#36 Adjacent difference
  include/nrng/adjacent_difference.hpp
  include/nrng/type_traits.hpp
  tests/adjacent_difference.test.cpp
  tests/type_traits.test.cpp
Labels: enhancement

#38 non-policy versions of transform_reduce
  include/nrng/transform_reduce.hpp
  tests/transform_reduce.test.cpp
Labels: enhancement

#39 Added goal statement to readme
  README.md
Labels: documentation

#41 Transform reduce
  include/nrng/reduce.hpp
  include/nrng/transform_reduce.hpp
  tests/transform_reduce.test.cpp
Labels: enhancement

#42 partial_sum + test
  include/nrng/partial_sum.hpp
  tests/partial_sum.test.cpp
Labels: enhancement
